### ISSUE TITLE
Building underlay sprites are in the wrong palette

### ISSUE THREAD

**Issue by drogoganor** [drogoganor/DarkReign#15]
![jungle-underlay](https://i.imgur.com/5LHkRI9.png)

There are different versions of the building underlay sprites for each tileset. Currently it is hard coded to the barren tileset in the sequences like so:

```
idle-top: barren|ncpow1l0.spr
	ZOffset: -8192
	Start: 1
```

This ncpow1I0.spr sprite file exists in each of the tileset archives: BARREN.FTG, SNOW.FTG, JUNGLE.FTG, etc.

But this hard-coding means it will only use the barren tileset underlay sprites, no matter what tileset we're using. This looks horrible as it's in the wrong palette, as seen above with the horrible green.

In the rules this sequence is shown using a `HitShape` and a `WithIdleOverlay`:

```
HitShape@LAYER1:
	Type: Rectangle
		TopLeft: -512, -1536
		BottomRight: 512, -512
WithIdleOverlay@LAYER1:
		Palette: terrain
		Sequence: idle-top
```

It will take code changes to create some way to load a sprite from the current tileset archive instead of hard-coding it like this.

**Comment by IceReaper** [comment]
Most likely you willneed a custom DarkReignBuildingSpriteBody trait. Maybe stuff like the CloakPaletteEffect will also help you.
