### ISSUE TITLE
Build fails for commit #105 (e91be6b) on Arch and openSUSE Tumbleweed

### ISSUE THREAD

**Issue by fusion809** [drogoganor/DarkReign#16]
Hi,

Commit 104 build absolutely fine on Arch and Tumbleweed, but 105's build failed with the error (no other warnings or issues elsewhere in the compile process):

```bash
CSC mods/d2k/OpenRA.Mods.D2k.dll
CSC OpenRA.Utility.exe
CSC OpenRA.Server.exe
make[1]: Leaving directory '/data/GitHub/others/DarkReign/engine'
Graphics/HackySpriteSequence.cs(242,24): error CS1501: No overload for method 'this' takes 2 arguments
Graphics/HackySpriteSequence.cs(259,16): error CS1501: No overload for method 'this' takes 2 arguments
Graphics/HackySpriteSequence.cs(272,15): error CS1501: No overload for method 'this' takes 2 arguments
Graphics/HackySpriteSequence.cs(285,18): error CS1729: 'SpriteWithSecondaryData' does not contain a constructor that takes 4 arguments
```

Based on this I'd guess these are the relevant lines to commit e91be6b: [242](https://github.com/drogoganor/DarkReign/commit/e91be6b3d33791d432b2bab764554d5fb5303b56#diff-92e2f6d411272399de37fa8683f4be40R242), [259](https://github.com/drogoganor/DarkReign/commit/e91be6b3d33791d432b2bab764554d5fb5303b56#diff-92e2f6d411272399de37fa8683f4be40R259), [272](https://github.com/drogoganor/DarkReign/commit/e91be6b3d33791d432b2bab764554d5fb5303b56#diff-92e2f6d411272399de37fa8683f4be40R272) and [285](https://github.com/drogoganor/DarkReign/commit/e91be6b3d33791d432b2bab764554d5fb5303b56#diff-92e2f6d411272399de37fa8683f4be40R285). 

Any fix to this issue will be much appreciated as this is a mighty fine mod :). 

Thanks for your time,
Brenton

**Comment by drogoganor** [comment]
Hi,

I believe you caught me right in the middle of updating the mod repo and the DR OpenRA branch it's using.

Please try a make clean and then make all, I believe that will work.

Cheers,
David

**Comment by fusion809** [comment]
Sorry mate, but it seems the error persists, despite pulling the latest commit. This time I'm building on elementary 5.0 beta 1, and I receive the error: 

```bash
Eluant.dll.config has been created successfully.
CSC fixheader.exe
CSC OpenRA.Game.exe
CSC OpenRA.Platforms.Default.dll
CSC mods/common/OpenRA.Mods.Common.dll
CSC mods/common/OpenRA.Mods.Cnc.dll
CSC mods/d2k/OpenRA.Mods.D2k.dll
CSC OpenRA.Utility.exe
CSC OpenRA.Server.exe
make[1]: Leaving directory '/data/GitHub/others/DarkReign/engine'
FileSystem/Ftg.cs(44,10): error CS0219: Warning as Error: The variable `identifier' is assigned but its value is never used
Graphics/HackySpriteSequence.cs(242,29): error CS1501: No overload for method `this' takes `2' arguments
Graphics/HackySpriteSequence.cs(248,27): error CS1928: Type `System.Collections.Generic.IEnumerable<OpenRA.Graphics.Sprite>' does not contain a member `Concat' and the best extension method overload `System.Linq.Enumerable.Concat<OpenRA.Graphics.Sprite>(this System.Collections.Generic.IEnumerable<OpenRA.Graphics.Sprite>, System.Collections.Generic.IEnumerable<OpenRA.Graphics.Sprite>)' has some invalid arguments
Graphics/HackySpriteSequence.cs(259,21): error CS1501: No overload for method `this' takes `2' arguments
Graphics/HackySpriteSequence.cs(272,20): error CS1501: No overload for method `this' takes `2' arguments
Graphics/HackySpriteSequence.cs(285,14): error CS1729: The type `OpenRA.Graphics.SpriteWithSecondaryData' does not contain a constructor that takes `4' arguments
```

I ran `make clean` before make, of course. By-the-way the `all` target doesn't exist in your Makefile, so `make all` simply returns a message saying there's no rule for it.

**Comment by fusion809** [comment]
Commit 107, 028c2c5, also doesn't fix this issue. I get the error: 

```bash
CSC OpenRA.Platforms.Default.dll
CSC mods/common/OpenRA.Mods.Common.dll
CSC mods/common/OpenRA.Mods.Cnc.dll
CSC mods/d2k/OpenRA.Mods.D2k.dll
CSC OpenRA.Utility.exe
CSC OpenRA.Server.exe
make[1]: Leaving directory '/data/GitHub/others/DarkReign/engine'
Graphics/HackySpriteSequence.cs(242,24): error CS1501: No overload for method 'this' takes 2 arguments
Graphics/HackySpriteSequence.cs(259,16): error CS1501: No overload for method 'this' takes 2 arguments
Graphics/HackySpriteSequence.cs(272,15): error CS1501: No overload for method 'this' takes 2 arguments
Graphics/HackySpriteSequence.cs(285,18): error CS1729: 'SpriteWithSecondaryData' does not contain a constructor that takes 4 arguments
```

**Comment by drogoganor** [comment]
Ah I see, I'm giving it a go now.

**Comment by drogoganor** [comment]
Ah I'm really sorry. I've only just committed the DarkReign repo now. Sorry for all the hassle.

**Comment by fusion809** [comment]
It's OK, you don't owe me anything, I'm just grateful for what you have done. Unfortunately, I still get an error:

```bash
Graphics/HackySpriteSequence.cs(242,24): error CS1501: No overload for method 'this' takes 2 arguments
Graphics/HackySpriteSequence.cs(259,16): error CS1501: No overload for method 'this' takes 2 arguments
Graphics/HackySpriteSequence.cs(272,15): error CS1501: No overload for method 'this' takes 2 arguments
Graphics/HackySpriteSequence.cs(285,18): error CS1729: 'SpriteWithSecondaryData' does not contain a constructor that takes 4 arguments
```

from `make clean ; make` (error in the make part of that, of course).

**Comment by drogoganor** [comment]
Hmm, I'm really not sure at this stage. Does the make clean actually remove the "engine" folder? If not you might have to rename that folder and try make again. Otherwise there must be a problem with the build scripts for linux or something.

**Comment by fusion809** [comment]
Ah you're right, it didn't remove the engine folder. Removing it fixed the error, thanks!

**Comment by drogoganor** [comment]
Great, thanks!
