### ISSUE TITLE
latest appimage doesnt ask for content

### ISSUE THREAD

**Issue by LiamDawe** [drogoganor/DarkReign#24]
Hello! Following this along with great anticipation, loved Dark Reign!

Tried out the most recent AppImage and it's supposed to ask for the content isn't it? All I get is a black screen with a Quit button currently.

**Comment by drogoganor** [comment]
Thanks for letting me know, I'll take a look

**Comment by drogoganor** [comment]
I'm pretty sure you caught me in the midst of some updates to the DR OpenRA repo and the DR repo itself. Could you please try getting the latest and trying again?

**Comment by LiamDawe** [comment]
Tried with the current master, didn't work when doing make:

> liam@liam-main:~/Downloads/DarkReign-master$ make
> OpenRA engine version playtest-20190106 is required.
> Downloading engine...
> Compiling engine...
> make[1]: Entering directory '/home/liam/Downloads/DarkReign-master/engine'
> make[1]: Leaving directory '/home/liam/Downloads/DarkReign-master/engine'
> make[1]: Entering directory '/home/liam/Downloads/DarkReign-master/engine'
> Fetching StyleCopPlus from NuGet
> Fetching StyleCop files from NuGet
> Fetching ICSharpCode.SharpZipLib from NuGet
> Fetching MaxMind.Db from NuGet
> Fetching SharpFont from NuGet
> Fetching NUnit from NuGet
> Fetching NUnit.Console from NuGet
> Fetching Open.Nat from NuGet
> Fetching FuzzyLogicLibrary from NuGet.
> Fetching SDL2-CS from GitHub.
> Fetching OpenAL-CS from GitHub.
> Fetching Eluant from GitHub.
> Fetching rix0rrr.BeaconLib from NuGet.
> Updating GeoIP country database from MaxMind.
> Detected Lua 5.1 library at /usr/lib/x86_64-linux-gnu/liblua5.1.so.0
> Eluant.dll.config has been created successfully.
> CSC fixheader.exe
> 
> Unhandled Exception:
> System.TypeInitializationException: The type initializer for 'System.Console' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.ConsoleDriver' threw an exception. ---> System.Exception: Magic number is wrong: 542
>   at System.TermInfoReader.ReadHeader (System.Byte[] buffer, System.Int32& position) [0x0002b] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.TermInfoReader..ctor (System.String term, System.String filename) [0x00065] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.TermInfoDriver..ctor (System.String term) [0x00058] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.ConsoleDriver.CreateTermInfoDriver (System.String term) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.ConsoleDriver..cctor () [0x00062] in <8f2c484307284b51944a1a13a14c0266>:0 
>    --- End of inner exception stack trace ---
>   at System.Console.SetupStreams (System.Text.Encoding inputEncoding, System.Text.Encoding outputEncoding) [0x0000a] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.Console..cctor () [0x000a8] in <8f2c484307284b51944a1a13a14c0266>:0 
>    --- End of inner exception stack trace ---
>   at Mono.CSharp.Driver.Main (System.String[] args) [0x00019] in <9494102539fd45149c591ed0d231421b>:0 
> [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Console' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.ConsoleDriver' threw an exception. ---> System.Exception: Magic number is wrong: 542
>   at System.TermInfoReader.ReadHeader (System.Byte[] buffer, System.Int32& position) [0x0002b] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.TermInfoReader..ctor (System.String term, System.String filename) [0x00065] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.TermInfoDriver..ctor (System.String term) [0x00058] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.ConsoleDriver.CreateTermInfoDriver (System.String term) [0x00000] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.ConsoleDriver..cctor () [0x00062] in <8f2c484307284b51944a1a13a14c0266>:0 
>    --- End of inner exception stack trace ---
>   at System.Console.SetupStreams (System.Text.Encoding inputEncoding, System.Text.Encoding outputEncoding) [0x0000a] in <8f2c484307284b51944a1a13a14c0266>:0 
>   at System.Console..cctor () [0x000a8] in <8f2c484307284b51944a1a13a14c0266>:0 
>    --- End of inner exception stack trace ---
>   at Mono.CSharp.Driver.Main (System.String[] args) [0x00019] in <9494102539fd45149c591ed0d231421b>:0 
> make[1]: *** [Makefile:259: fixheader.exe] Error 1
> make[1]: Leaving directory '/home/liam/Downloads/DarkReign-master/engine'
> make: *** [Makefile:99: engine] Error 2
>

**Comment by GraionDilach** [comment]
@LiamDawe please see https://github.com/mono/mono/issues/6752#issuecomment-365212655

That's a particular Mono bug in your version.

**Comment by LiamDawe** [comment]
Ah, that's a nuisance one. Had to do: "TERM=xterm" first.

New issue, when trying to run it with the "launch-game.sh" file I get this:

> liam@liam-main:~/Downloads/DarkReign-master$ '/home/liam/Downloads/DarkReign-master/launch-game.sh' 
> Platform is Linux
> Engine version is playtest-20190106
> Using SDL 2 with OpenGL renderer
> Desktop resolution: 1920x1080
> No custom resolution provided, using desktop resolution
> Using resolution: 1920x1080
> Using window scale 1.00
> OpenGL version: 4.6.0 NVIDIA 415.27
> Using default sound device
> Internal mods:
> 	dr: Dark Reign ({DEV_VERSION})
> 	modcontent: Mod Content Manager (playtest-20190106)
> 	all: All mods (playtest-20190106)
> 	cnc: Tiberian Dawn (playtest-20190106)
> 	d2k: Dune 2000 (playtest-20190106)
> 	ra: Red Alert (playtest-20190106)
> 	ts: Tiberian Sun (playtest-20190106)
> External mods:
> 	dr-{DEV_VERSION}: Dark Reign ({DEV_VERSION})
> Loading mod: dr
> Exception of type `System.IO.FileNotFoundException`: File not found: dr|chrome/mainmenu-prerelease-notification.yaml
>   at OpenRA.FileSystem.FileSystem.Open (System.String filename) [0x00023] in <331b1b97f0c14e81a22344489f40b50a>:0 
>   at OpenRA.WidgetLoader+<WidgetLoader>c__AnonStorey0.<>m__0 (System.String a) [0x0000b] in <331b1b97f0c14e81a22344489f40b50a>:0 
>   at System.Linq.Enumerable+WhereSelectArrayIterator`2[TSource,TResult].MoveNext () [0x0004d] in <63992662b765477a898ef49cdcc99ee2>:0 
>   at OpenRA.WidgetLoader..ctor (OpenRA.ModData modData) [0x000ff] in <331b1b97f0c14e81a22344489f40b50a>:0 
>   at OpenRA.ModData..ctor (OpenRA.Manifest mod, OpenRA.InstalledMods mods, System.Boolean useLoadScreen) [0x00103] in <331b1b97f0c14e81a22344489f40b50a>:0 
>   at OpenRA.Game.InitializeMod (System.String mod, OpenRA.Arguments args) [0x00167] in <331b1b97f0c14e81a22344489f40b50a>:0 
>   at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x004c7] in <331b1b97f0c14e81a22344489f40b50a>:0 
>   at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00007] in <331b1b97f0c14e81a22344489f40b50a>:0 
>   at OpenRA.Program.Main (System.String[] args) [0x0004f] in <331b1b97f0c14e81a22344489f40b50a>:0

**Comment by drogoganor** [comment]
Sorry I missed a file in the latest commit. It's been added now and the build is passing.

**Comment by drogoganor** [comment]
This should be resolved now. Could you let me know if the mod works for you now?

**Comment by LiamDawe** [comment]
Much better but still has issues.

It will ask for content, so i click quick install and it downloads the demo content but then it claims again it needs it. I went to the advanced option, to see another bit was required and that was easy enough to download too.

Seems the warning about needing to download stuff, doesn't detect that it needs to switch to download the other bit apart from the demo?

**Comment by drogoganor** [comment]
This should be solved by now, thanks for taking the time.
