### ISSUE TITLE
Medics and mechanics continuously heal/repair units

### ISSUE THREAD

**Issue by drogoganor** [drogoganor/DarkReign#25]
A recent update requires healing to be contingent on a condition. I've done the following to support this:

^Humanoid:
	GrantConditionOnDamageState@DAMAGED:
		Condition: damaged
		ValidDamageStates: Light, Medium, Heavy, Critical
	Targetable@HEAL:
		RequiresCondition: damaged
		TargetTypes: Heal

And weapon:

Heal:
	ReloadDelay: 135
	Range: 2c512
	Report: gxheaoc0.wav
	ValidTargets: Infantry
	Projectile: Bullet
		Speed: 1c682
	Warhead@1Dam: SpreadDamage
		Spread: 256
		Damage: -85
		ValidStances: Ally
		ValidTargets: Infantry
		DebugOverlayColor: 00FF00

Repair:
	Inherits: Heal
	ReloadDelay: 150
	Report: gxrepoc0.wav
	ValidTargets: Repair
	Warhead@1Dam: SpreadDamage
		Damage: -85
		ValidTargets: Repair

But medics and mechanics continuously repair/heal at full health. I must be missing something.

**Comment by GraionDilach** [comment]
>ValidTargets: Infantry

Should be Heal here for sure.

**Comment by drogoganor** [comment]
Resolved, thanks @GraionDilach
