### ISSUE TITLE
Shock wave does not work

### ISSUE THREAD

**Issue by drogoganor** [drogoganor/DarkReign#28]
Shattered Paradise apparently has a weapon like this.

**Comment by GraionDilach** [comment]
If there is something from SP or logicwise akin, ping me on a common channel. I provide the technical support over there and I'm fairly sure I can pinpoint the exact classes involved.

How is this shockwave supposed to work btw?

**Comment by drogoganor** [comment]
Thanks. Here's how the shockwave works:

https://www.youtube.com/watch?v=EID9Uk7OBD0

I was working on it last night based on your WarheadTrailProjectile (which is fun), and am proceeding ok. Thanks for your feedback on the other bugs too.

**Comment by GraionDilach** [comment]
It's @CDVoidwalker's, actually, but yeah, that's what I would have suggested to start with.

**Comment by CDVoidwalker** [comment]
To be honest, doesn't look that hard to implement as additional FireMode for that @drogoganor , if you'd like me to work on it I could add that.

**Comment by GraionDilach** [comment]
Void, https://github.com/drogoganor/DarkReign/tree/master/OpenRA.Mods.Dr/Effects :P

**Comment by drogoganor** [comment]
This one has actually been completed as of last night.

![shockwave](https://user-images.githubusercontent.com/1639681/52017848-54a2e700-2534-11e9-96b4-4eeb71a5b5d3.gif)

**Comment by drogoganor** [comment]
Yeah that WarheadTrailProjectile was the bomb, thanks
