### ISSUE TITLE
Game complains of missing assets, even when they are present and even after running "Quick Install" again

### ISSUE THREAD

**Issue by fusion809** [drogoganor/DarkReign#34]
Hi,

I'm shown this screen upon starting up DarkReign:

![screenshot_20190207_025939](https://user-images.githubusercontent.com/4717341/52358873-7ea06000-2a84-11e9-94b7-f44e1fc27855.png)

Even when I have the assets already installed. I clicked "Quick Install" in case you recently edited the game to require new assets, yet I'm still taken back to this screen after it is complete. 

Thanks for your time,
Brenton

**Comment by LiamDawe** [comment]
Related https://github.com/drogoganor/DarkReign/issues/24

It's because it requires two sets of content but doesn't seem to grab both.

**Comment by drogoganor** [comment]
Alright, yes this is currently a known limitation of the installer at the moment. Auran released a set of free assets for Dark Reign which are integrated with this mod, but they have to be downloaded separately, under Advanced Install.

If you click Advanced Install it should have a row "Auran Extras". Click Download to the right of this to download the content. Then you should be able to proceed. Hope this works for you.
