### ISSUE TITLE
Question: How do you generate maps

### ISSUE THREAD

**Issue by siredmar** [drogoganor/DarkReign#40]
Just wondering how to support the project with more maps. 
How did you generate those maps? Are they "made" manually or did you use some sort of tool to convert original Dark Reign scenarios to your mod?

Maybe i can write some conversion tool. Could you give me some information on that?

**Comment by drogoganor** [comment]
Hello,

Maps can be created using the inbuilt map editor accessed from Main Menu -> Extras -> Map Editor.

There's actually a tool to convert maps from the original game, detailed here: https://github.com/drogoganor/DarkReign/wiki/Utility-features

Although please note the functionality is very limited for the single player maps. No scripting is included.

I was going to resume work on the mod and hopefully create some custom single player maps once the new savegame feature makes its way into the main branch: https://www.openra.net/news/preview-20190606/?fbclid=IwAR02jnC_UuW_YzGkNBoQzva7uqUwCNOnAS1oEt-BNQyhzfzroAS1z9xMEXQ

But I'd certainly love to see some new maps, single or multi, made for the mod!
