### ISSUE TITLE
DR's PaletteFromJascFile duplicate should be removed

### ISSUE THREAD

**Issue by GraionDilach** [drogoganor/DarkReign#41]
I see you did that for the Gamma alteration and maybe for Jasc32, but IIRC Jasc32 is in upstream by now, and gamma offsetting fits better for an explicit PaletteFromPaletteWithGamma trait.

**Comment by drogoganor** [comment]
Thank you for the advice. I do intend to keep this mod up to date once ORA reaches it's next release.

**Comment by drogoganor** [comment]
It's done!
