### ISSUE TITLE
No shadows on units, buildings, or decorations

### ISSUE THREAD

**Issue by drogoganor** [drogoganor/DarkReign#5]
DR shadow images are separate .spr files from the unit, building, or decoration .spr files. Currently we can manually add them together like so for decorations:

Sequence:
```
aoclf000.spr:
	Defaults:
		AddExtension: False
	idle:
		Start: 0
		Length: 1
	shadow: aoclf0sh.spr
		Start: 0
		Length: 1
		Offset: 13, 12
```

Rule:
```
aoclf000.spr:
	Inherits: ^DrRock
	Building:
		Footprint: __ x_
		Dimensions: 2,2
	HitShape@LAYER1:
		Type: Rectangle
			TopLeft: -512, -512
			BottomRight: 512, 512
	WithIdleOverlay@LAYER1:
		Palette: shadow
		Sequence: shadow
```

But I'm not sure how we're going to handle units which have direction and animation. There is also a ton of work involved in devising the Offset of the shadow for all the units, buildings and decorations.

**Comment by drogoganor** [comment]
A lot of shadows have been added to decorations and buildings. Units with animations still an unknown.

**Comment by pchote** [comment]
Take a look at how the split shadows are defined in OpenRA's TS mod.  You should be able to use the sequence Combine tag to stitch the normal and shadow sprites together, then define appropriate shadow offsets.

**Comment by drogoganor** [comment]
Shadows have been mostly implemented, but tileset-specific shadows for decorations need to use the hotspot data to devise the offset. Closing.
